[package]
name = "aoc2022rust"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.1"
regex = "1.1.9"
lazy_static = "1.4.0"
lazy-regex = "2.4.1"
grid = "0.9.0"
num = "0.4.0"
fnv = "1.0.7"